### ISSUE TITLE
Link-time Code Generation with MSVC 15.7 issue

### ISSUE THREAD

**Issue by nono303** [OSTC/php-sdk-binary-tools#36] opened 2018-06-12 14:38 UTC
Hi,
Since **MSVC 15.7** update, I can't anymore build with Link-time Code Generation
Ex.

- With **/LTCG** for LDFLAGS and **/GL** for ARFLAGS & CFLAGS:
  - `fatal error C1047: Le fichier objet ou le fichier bibliothèque 'C:\php72-sdk\phpmaster\vc15\x86\deps\lib\libiconv_a.lib' a été créé à l'aide d'un compilateur antérieur à celui d'autres objets ; régénérez les objets et bibliothèques obsolètes`
- Without /LTCG for LDFLAGS and /GL for ARFLAGS & CFLAGS:
  - `libiconv_a.lib(iconv1.obj) : .netmodule ou module MSIL compilé avec /GL trouvé ; redémarrage de l'édition de liens avec /LTCG ; ajoutez /LTCG à la ligne de commande de l'édition de liens pour améliorer les performances de l'Éditeur de liens`
  - And same message for freetype_a.lib

For details about MSVC version, here are
- The last one with Link-time Code Generation OK https://github.com/nono303/phpwin-perfbuild/tree/php-7.2.5 
- The new one without it https://github.com/nono303/phpwin-perfbuild/tree/php-7.2.6

Do you think it would be possible to update libiconv and freetype dependencies build either with: 
- **MSVC 15.7 (cl 19.14)**
- **without /GL CFLAGS**

Don't hesitate to come back to me if needed.

**Comment by nono303** [comment] 2018-06-13 08:00
I've overridden problematic dependencies with MSVC 15.7 and without /GL & /LTCG ones: and it's works ;)

the 4 deps are available @ https://github.com/nono303/phpwin-perfbuild/tree/php-7.2.6/vc15/x64/deps & https://github.com/nono303/phpwin-perfbuild/tree/php-7.2.6/vc15/x86/deps

fyi, php 7.2.6 bench results with [Zend/micro_bench.php](https://github.com/php/php-src/blob/master/Zend/micro_bench.php) give an average of 4.595 for unoptimized build and 4.169 for /GL & /LTCG one

**Comment by weltling** [comment] 2018-06-13 09:06
Thanks for the report. We didn't switch to 15.7 for the official builds yet because of some other compatibility issues. It's going to be upgraded after the test phase. Of course any dep issues are going to be fixed, too.

Regarding performance - do you have benchmarks with some real apps? For the builds from windows.php.net /LTCG is used for the PGO builds, too. Did you use PGO as well? It would probably make sense to describe in some more detail the methodology of your test. Synthetic benchmarks are often not representative, what matters are the real apps where one wants to see the effect.

Thanks.

**Comment by nono303** [comment] 2018-06-13 13:23
@weltling 

- _do you have benchmarks with some real apps_ 
  => No, I use these build for ~twenty low traffic websites, so don’t have any figure on real apps performance improvement.
- _Did you use PGO as well_ 
  => I used to but instrumentation take me (too much?) time for a few subset of php function that was not exhaustive

In truth, i play with php compilation for fun & knowledge ^^

**Comment by weltling** [comment] 2018-06-25 06:51
Upgraded dependencies have been put into staging, so the issue is fixed now.

Thanks.

**Closed as completed by weltling** 2018-06-25 06:51 UTC

**Comment by nono303** [comment] 2018-07-24 09:42
@weltling 
Thanks! All sounds good with php-sdk-2.1.7 and php-7.2.8 ;)
fyi, find attached my phpsdk-local.bat & output.log
[phpsdk-local.bat.txt](https://github.com/Microsoft/php-sdk-binary-tools/files/2222977/phpsdk-local.bat.txt)
[x64_TS-0_LTCG-1_20180724-111549.log](https://github.com/Microsoft/php-sdk-binary-tools/files/2222978/x64_TS-0_LTCG-1_20180724-111549.log)

**Comment by nono303** [comment] 2018-08-16 12:51
Hi,
@weltling fyi, same problem with MSVC 15.8 update.
I've uploaded x86 & x64 15.8 build deps on https://github.com/nono303/phpwin-perfbuild/tree/php-7.2.9
