### ISSUE TITLE
Can't build PHP 7.1.11 on Windows 10 x64

### ISSUE THREAD

**Issue by kalayda** [OSTC/php-sdk-binary-tools#21] opened 2017-11-13 05:10 UTC
I try to build PHP 7.1.11 on Windows 10 x64 according to new  [building manual]
(https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2)
Have installed Visual Studio Community 2015 (full installation, all the components).

When running phpsdk-vc14-x64.bat error message occuring
```
ERROR: The system was unable to find the specified registry key or value.
Windows SDK not found.
```
It happen because `bin\phpsdk_setshell.bat` try to check registry for `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v8.1`

But name of this key in my system's registry is **v8.1A**

Also, there is no `Include `directory in SDK's installation path.

May be problem is in Community VS edition? Should I use Professional, or Enterprise one?

**Comment by weltling** [comment] 2017-11-14 18:09
Thanks for the report. Do you have the latest VS version? Of course, we can fallback to lookup for another SDK version, but i actually wouldn't recommend it. PHP core might be ok, but all the dependencies are also using a newer SDK. 

Thanks.

**Comment by weltling** [comment] 2017-11-15 19:14
I was just checking setups on several machines. The installation paths shown in the registry 

8.1 - C:\Program Files (x86)\Windows Kits\8.1
8.1a - C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A

The latter doesn't contain any useful stuff for us - no headers, no libs, etc. v8.1a was added in VS2013 and it seems it requires 8.1 to actually work properly. At this point it seems that something went wrong with the setup on your side, thus closing as not a bug.

Thanks.

**Closed as completed by weltling** 2017-11-15 19:14 UTC

**Comment by weltling** [comment] 2017-11-15 19:16
Also please keep in mind, that we don't officially support the new SDK for PHP versions < 7.2. You can try to use in in the old way by caling vcvarsall.bat manually, or you can switch to the old SDK.

Thanks.
